
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2024/11/19 9:04:14。
      节点 1 上的项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.44
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2024/11/19 9:04:16。
      节点 1 上的项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.24
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yza6ij"
      binary: "C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yza6ij"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yza6ij'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_275b7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2024/11/19 9:04:18。
        节点 1 上的项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-yza6ij\\cmTC_275b7.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_275b7.dir\\Debug\\”。
          正在创建目录“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-yza6ij\\Debug\\”。
          正在创建目录“cmTC_275b7.dir\\Debug\\cmTC_275b7.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_275b7.dir\\Debug\\cmTC_275b7.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_275b7.dir\\Debug\\\\" /Fd"cmTC_275b7.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "E:\\IDE\\apps\\CLion\\ch-0\\241.15989.121\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31332 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCCompilerABI.c
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_275b7.dir\\Debug\\\\" /Fd"cmTC_275b7.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "E:\\IDE\\apps\\CLion\\ch-0\\241.15989.121\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-yza6ij\\Debug\\cmTC_275b7.exe" /INCREMENTAL /ILK:"cmTC_275b7.dir\\Debug\\cmTC_275b7.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yza6ij/Debug/cmTC_275b7.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-yza6ij/Debug/cmTC_275b7.lib" /MACHINE:X64  /machine:x64 cmTC_275b7.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_275b7.vcxproj -> C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-yza6ij\\Debug\\cmTC_275b7.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_275b7.dir\\Debug\\cmTC_275b7.tlog\\unsuccessfulbuild”。
          正在对“cmTC_275b7.dir\\Debug\\cmTC_275b7.tlog\\cmTC_275b7.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-yza6ij\\cmTC_275b7.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.10
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/IDE/apps/CLion/ch-0/241.15989.121/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8j9gfz"
      binary: "C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8j9gfz"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8j9gfz'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_b70ee.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2024/11/19 9:04:19。
        节点 1 上的项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8j9gfz\\cmTC_b70ee.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_b70ee.dir\\Debug\\”。
          正在创建目录“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8j9gfz\\Debug\\”。
          正在创建目录“cmTC_b70ee.dir\\Debug\\cmTC_b70ee.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_b70ee.dir\\Debug\\cmTC_b70ee.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b70ee.dir\\Debug\\\\" /Fd"cmTC_b70ee.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "E:\\IDE\\apps\\CLion\\ch-0\\241.15989.121\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31332 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b70ee.dir\\Debug\\\\" /Fd"cmTC_b70ee.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "E:\\IDE\\apps\\CLion\\ch-0\\241.15989.121\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8j9gfz\\Debug\\cmTC_b70ee.exe" /INCREMENTAL /ILK:"cmTC_b70ee.dir\\Debug\\cmTC_b70ee.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8j9gfz/Debug/cmTC_b70ee.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/17305/CLionProjects/QtSpy/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8j9gfz/Debug/cmTC_b70ee.lib" /MACHINE:X64  /machine:x64 cmTC_b70ee.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_b70ee.vcxproj -> C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8j9gfz\\Debug\\cmTC_b70ee.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_b70ee.dir\\Debug\\cmTC_b70ee.tlog\\unsuccessfulbuild”。
          正在对“cmTC_b70ee.dir\\Debug\\cmTC_b70ee.tlog\\cmTC_b70ee.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\17305\\CLionProjects\\QtSpy\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8j9gfz\\cmTC_b70ee.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.08
        
      exitCode: 0
...
